// for Login Api Action type

export const SET_MQTT_CLIENT = 'SET_MQTT_CLIENT'

export const LOG_IN_INIT = 'LOG_IN_INIT'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAIL = 'LOG_IN_FAIL'

export const SIGN_UP_INIT = 'SIGN_UP_INIT'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'

export const SIGN_OUT = 'SIGN_OUT'

export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL'

export const USER_ROLES_INIT = 'USER_ROLES_INIT'
export const USER_ROLES_SUCCESS = 'USER_ROLES_SUCCESS'
export const USER_ROLES_FAIL = 'USER_ROLES_FAIL'

// For Validate Email And Password From AD
export const VALIDATE_EMAIL_PASSWORD_INIT = 'VALIDATE_EMAIL_PASSWORD_INIT'
export const VALIDATE_EMAIL_PASSWORD_SUCCESS = 'VALIDATE_EMAIL_PASSWORD_SUCCESS'
export const VALIDATE_EMAIL_PASSWORD_FAIL = 'VALIDATE_EMAIL_PASSWORD_FAIL'

export const GET_RECENT_QUOTE_TBILL = 'GET_RECENT_QUOTE_TBILL'
export const GET_RECENT_QUOTE_TBILL_SUCCESS = 'GET_RECENT_QUOTE_TBILL_SUCCESS'
export const GET_RECENT_QUOTE_TBILL_FAIL = 'GET_RECENT_QUOTE_TBILL_FAIL'

export const GET_RECENT_QUOTE_PIB = 'GET_RECENT_QUOTE_PIB'
export const GET_RECENT_QUOTE_PIB_SUCCESS = 'GET_RECENT_QUOTE_PIB_SUCCESS'
export const GET_RECENT_QUOTE_PIB_FAIL = 'GET_RECENT_QUOTE_PIB_FAIL'

export const GET_RECENT_QUOTE_PIB_FLOATER = 'GET_RECENT_QUOTE_PIB_FLOATER'
export const GET_RECENT_QUOTE_PIB_FLOATER_SUCCESS =
  'GET_RECENT_QUOTE_PIB_FLOATER_SUCCESS'
export const GET_RECENT_QUOTE_PIB_FLOATER_FAIL =
  'GET_RECENT_QUOTE_PIB_FLOATER_FAIL'

export const GET_RECENT_QUOTE_SUKUK = 'GET_RECENT_QUOTE_SUKUK'
export const GET_RECENT_QUOTE_SUKUK_SUCCESS = 'GET_RECENT_QUOTE_SUKUK_SUCCESS'
export const GET_RECENT_QUOTE_SUKUK_FAIL = 'GET_RECENT_QUOTE_SUKUK_FAIL'

export const GET_OUTSTANDING_DETAILS = 'GET_OUTSTANDING_DETAILS'
export const GET_OUTSTANDING_DETAILS_SUCCESS = 'GET_OUTSTANDING_DETAILS_SUCCESS'
export const GET_OUTSTANDING_DETAILS_FAIL = 'GET_OUTSTANDING_DETAILS_FAIL'

export const UPDATE_VOLMETER = 'UPDATE_VOLMETER'
export const UPDATE_VOLMETER_SUCCESS = 'UPDATE_VOLMETER_SUCCESS'
export const UPDATE_VOLMETER_FAIL = 'UPDATE_VOLMETER_FAIL'

export const GET_VOLMETER_BY_BANKID = 'GET_VOLMETER_BY_BANKID'
export const GET_VOLMETER_BY_BANKID_SUCCESS = 'GET_VOLMETER_BY_BANKID_SUCCESS'
export const GET_VOLMETER_BY_BANKID_FAIL = 'GET_VOLMETER_BY_BANKID_FAIL'
